@extends('layouts.admin')
@section('title', $campaign->exists ? 'Edit campaign' : 'Create campaign')
@section('heading', $campaign->exists ? 'Edit campaign' : 'Create campaign')
@section('content')
<form class="form-stack" method="POST" action="{{ $campaign->exists ? route('advertiser.campaigns.update',$campaign) : route('advertiser.campaigns.store') }}">@csrf @if($campaign->exists)@method('PUT')@endif
<section class="detail-grid"><article><p class="eyebrow">Campaign</p><h2>Plan</h2>
<label>Name<input class="hm-input" name="name" value="{{ old('name',$campaign->name) }}" required></label><label>Objective<input class="hm-input" name="objective" value="{{ old('objective',$campaign->objective) }}" placeholder="Awareness, traffic, video views…" required></label>
<label>Pricing model<select class="hm-input" name="pricing_model">@foreach(\App\Enums\CampaignPricingModel::cases() as $model)<option value="{{ $model->value }}" @selected(old('pricing_model',$campaign->pricing_model?->value)===$model->value)>{{ $model->value }}</option>@endforeach</select></label>
<div class="form-grid"><label>Starts<input class="hm-input" type="datetime-local" name="starts_at" value="{{ old('starts_at',$campaign->starts_at?->format('Y-m-d\TH:i')) }}" required></label><label>Ends<input class="hm-input" type="datetime-local" name="ends_at" value="{{ old('ends_at',$campaign->ends_at?->format('Y-m-d\TH:i')) }}" required></label><label>Currency<input class="hm-input" name="currency" value="{{ old('currency',$campaign->currency ?: 'USD') }}" maxlength="3" required></label><label>Total budget<input class="hm-input" type="number" step="0.01" min="0" name="total_budget" value="{{ old('total_budget',number_format(($campaign->total_budget_minor ?? 0)/100,2,'.','')) }}" required></label><label>Daily budget<input class="hm-input" type="number" step="0.01" min="0" name="daily_budget" value="{{ old('daily_budget',$campaign->daily_budget_minor ? number_format($campaign->daily_budget_minor/100,2,'.','') : '') }}"></label><label>Unit price<input class="hm-input" type="number" step="0.01" min="0" name="unit_price" value="{{ old('unit_price',$campaign->budget?->unit_price_minor ? number_format($campaign->budget->unit_price_minor/100,2,'.','') : '') }}"></label><label>Impression goal<input class="hm-input" type="number" min="0" name="impression_goal" value="{{ old('impression_goal',$campaign->goals?->firstWhere('goal_type','IMPRESSIONS')?->target_value) }}"></label><label>Click goal<input class="hm-input" type="number" min="0" name="click_goal" value="{{ old('click_goal',$campaign->goals?->firstWhere('goal_type','CLICKS')?->target_value) }}"></label><label>Frequency cap<input class="hm-input" type="number" min="1" name="frequency_cap_impressions" value="{{ old('frequency_cap_impressions',$campaign->frequency_cap_impressions) }}"></label><label>Cap period days<input class="hm-input" type="number" min="1" max="90" name="frequency_cap_days" value="{{ old('frequency_cap_days',$campaign->frequency_cap_days) }}"></label></div>
<label>Landing URL<input class="hm-input" type="url" name="landing_url" value="{{ old('landing_url',$campaign->landing_url) }}"></label><label>Notes<textarea class="hm-input" name="advertiser_notes" rows="4">{{ old('advertiser_notes',$campaign->advertiser_notes) }}</textarea></label>
</article><article><p class="eyebrow">Targeting</p><h2>Audience and inventory</h2>
<label>Countries (hold Ctrl/⌘ for multiple)<select class="hm-input" name="countries[]" multiple size="6">@foreach(['EG','SA','AE','US','GB','CA','DE','FR'] as $country)<option @selected(in_array($country,old('countries',$campaign->targets?->firstWhere('dimension','COUNTRY')?->values ?? [])))>{{ $country }}</option>@endforeach</select></label>
<label>Devices<select class="hm-input" name="devices[]" multiple size="4">@foreach(['DESKTOP','TABLET','MOBILE','CONNECTED_TV'] as $device)<option @selected(in_array($device,old('devices',$campaign->targets?->firstWhere('dimension','DEVICE')?->values ?? [])))>{{ $device }}</option>@endforeach</select></label>
<p class="muted">Every selected website is deployed automatically to its currently selected GAM network. HORUS_GAM is used by default.</p>
@php($selectedSites=old('site_ids',$campaign->sites?->pluck('site_id')->all() ?? []))@php($selectedPlacements=old('placement_ids',$campaign->placements?->pluck('placement_id')->all() ?? []))
@foreach($sites as $site)<div class="domain-card"><label><input type="checkbox" name="site_ids[]" value="{{ $site->id }}" @checked(in_array($site->id,$selectedSites))> <strong>{{ $site->display_name }}</strong> · {{ $site->publisher->display_name }} · {{ $site->serving_mode->value }}</label>@foreach($placements->where('site_id',$site->id) as $placement)<label style="margin-left:1.5rem"><input type="checkbox" name="placement_ids[]" value="{{ $placement->id }}" @checked(in_array($placement->id,$selectedPlacements))> {{ $placement->name }} ({{ $placement->code }})</label>@endforeach</div>@endforeach
</article></section><button class="hm-button-primary">{{ $campaign->exists ? 'Save campaign' : 'Create campaign' }}</button></form>
@endsection
