@extends('layouts.admin')
@section('title', $campaign->name)
@section('heading', $campaign->name)
@section('content')
<section class="hero"><div><p class="eyebrow">{{ $campaign->public_key }}</p><h2>{{ $campaign->objective }}</h2><div class="status-row"><span class="pill">{{ $campaign->status->value }}</span><span class="pill">{{ $campaign->pricing_model->value }}</span><span class="pill">{{ $campaign->currency }} {{ number_format($campaign->total_budget_minor/100,2) }}</span><span class="pill">{{ $campaign->starts_at }} → {{ $campaign->ends_at }}</span></div></div>@if(in_array($campaign->status->value,['DRAFT','REJECTED']) && $deliveryCapability['available'])<form method="POST" action="{{ route('advertiser.campaigns.submit',$campaign) }}">@csrf<button class="hm-button-primary">Submit for approval</button></form>@endif</section>
<article style="margin-top:1rem"><p class="eyebrow">Delivery backend</p><h2>{{ $deliveryCapability['status']==='READY' ? 'Ready' : 'Delivery unavailable' }}</h2><p class="{{ $deliveryCapability['available'] ? 'muted' : 'error' }}">{{ $deliveryCapability['message'] }}</p>@if(!$deliveryCapability['available'] && in_array($campaign->status->value,['DRAFT','REJECTED']))<p class="muted">Your draft remains saved. Delivery is not promised until readiness is restored.</p>@endif</article>
<section class="metric-grid">@foreach([['Impressions',number_format($report['impressions'])],['Clicks',number_format($report['clicks'])],['Views',number_format($report['views'])],['Spend',$campaign->currency.' '.number_format($report['spend_minor']/100,2)]] as [$label,$value])<article><p class="eyebrow">{{ $label }}</p><strong class="metric-small">{{ $value }}</strong></article>@endforeach</section>
<section class="detail-grid"><article><p class="eyebrow">Inventory</p><h2>Publishers, websites, placements</h2>@foreach($campaign->sites as $row)<div class="domain-card"><strong>{{ $row->site->display_name }}</strong><span>{{ $row->site->publisher->display_name }}</span></div>@endforeach<p class="muted">{{ $campaign->placements->count() ? $campaign->placements->count().' selected placements' : 'All active placements on selected websites' }}</p></article>
<article><p class="eyebrow">Delivery status</p><h2>Delivery routes</h2>@forelse($campaign->networkInstances as $instance)<div class="event"><div><strong>Horus-managed route</strong><br><span>{{ str($instance->status->value)->replace('_',' ')->headline() }}</span></div><span>{{ $campaign->currency }} {{ number_format($instance->budget_allocated_minor/100,2) }}</span></div>@empty<p class="muted">Delivery routes are prepared during campaign review.</p>@endforelse</article></section>
<article><div class="section-heading"><div><p class="eyebrow">Validated assets</p><h2>Creatives</h2></div></div>@foreach($campaign->creatives as $creative)<div class="domain-card"><div><strong>{{ $creative->name }}</strong><div class="status-row"><span class="pill">{{ $creative->type->value }}</span><span class="pill">{{ $creative->status->value }}</span><span class="pill">{{ $creative->width }}×{{ $creative->height }}</span></div>@if($creative->rejection_reason)<p class="error">{{ $creative->rejection_reason }}</p>@endif</div></div>@endforeach
<form class="form-stack" method="POST" enctype="multipart/form-data" action="{{ route('advertiser.campaigns.creatives.store',$campaign) }}">@csrf<h3>Upload creative</h3><div class="form-grid"><label>Name<input class="hm-input" name="name" required></label><label>Type<select class="hm-input" name="type">@foreach(\App\Enums\CampaignCreativeType::cases() as $type)<option value="{{ $type->value }}">{{ $type->value }}</option>@endforeach</select></label><label>File<input class="hm-input" type="file" name="creative_file"></label><label>Width<input class="hm-input" type="number" name="width"></label><label>Height<input class="hm-input" type="number" name="height"></label><label>Click-through URL<input class="hm-input" type="url" name="click_through_url"></label><label class="full">HTML or third-party tag<textarea class="hm-input" name="html_content"></textarea></label><label class="full">Native assets JSON<textarea class="hm-input" name="native_assets_json"></textarea></label><label>VAST URL<input class="hm-input" type="url" name="vast_url"></label><label>Text content<input class="hm-input" name="text_content"></label></div><button class="hm-button-secondary">Validate and upload</button></form></article>
@if($campaign->invoices->isNotEmpty())<article><h2>Invoices</h2>@foreach($campaign->invoices as $invoice)<a class="hm-button-secondary" href="{{ route('advertiser.invoices.download',$invoice) }}">Download {{ $invoice->invoice_number }}</a>@endforeach</article>@endif
@endsection
