@props(['rows', 'currency', 'publisher' => false, 'label' => 'Date', 'totals' => null])
@php
    $caption = $label === 'Date' ? 'Video daily performance' : 'Video website performance';
    $revenueLabel = $publisher ? 'Video earnings' : 'Video gross revenue';
@endphp
<p class="video-table-context">Unfilled: selected ad unit, all sites. Revenue and impressions: matched website.</p>
<div class="table-wrap report-performance-table report-performance-table--responsive video-performance-table" tabindex="0" role="region" aria-label="{{ $caption }}">
<table><caption class="sr-only">{{ $caption }} · {{ $currency }}</caption><thead><tr><th scope="col">{{ $label }}</th><th scope="col">Impressions</th><th scope="col">Unfilled <small>(all sites)</small></th><th scope="col">{{ $revenueLabel }} <small>({{ $currency }})</small></th><th scope="col">eCPM <small>({{ $currency }})</small></th>@unless($publisher)<th scope="col">Publisher earnings <small>({{ $currency }})</small></th><th scope="col">Horus margin <small>({{ $currency }})</small></th>@endunless</tr></thead>
<tbody>@foreach($rows as $row)<tr><th scope="row">@if($label === 'Website' && !$publisher && ($row['site_id'] ?? null))<a class="text-link" href="{{ route('admin.reporting.websites.show', ['site' => $row['site_id'], 'from' => request('from'), 'to' => request('to')]) }}">{{ $row['label'] }}</a>@else{{ $row[$label === 'Date' ? 'date' : 'label'] }}@endif @if($label === 'Website' && ($row['domain'] ?? null))<small class="video-row-domain">{{ $row['domain'] }}</small>@endif @if($row['has_estimates'])<small class="video-row-state">Estimated</small>@endif</th><td>{{ $row['impressions'] === null ? 'Unavailable' : \App\Services\Reporting\PerformanceMetrics::display('impressions', $row['impressions']) }}</td><td>{{ $row['unfilled_impressions'] === null ? 'Unavailable' : \App\Services\Reporting\PerformanceMetrics::display('unfilled_impressions', $row['unfilled_impressions']) }}</td><td class="money">{{ \App\Support\Money::formatMinor($row['revenue_minor']) }}</td><td>{{ $row['ecpm_minor'] === null ? 'Unavailable' : \App\Services\Reporting\PerformanceMetrics::display('ecpm_minor', $row['ecpm_minor']) }}</td>@unless($publisher)<td>{{ \App\Support\Money::formatMinor($row['publisher_earnings_minor']) }}</td><td>{{ \App\Support\Money::formatMinor($row['horus_earnings_minor']) }}</td>@endunless</tr>@endforeach</tbody>
@if($totals)<tfoot><tr><th scope="row">Period total</th><td>{{ $totals['impressions'] === null ? 'Unavailable' : \App\Services\Reporting\PerformanceMetrics::display('impressions', $totals['impressions']) }}</td><td>{{ $totals['unfilled_impressions'] === null ? 'Unavailable' : \App\Services\Reporting\PerformanceMetrics::display('unfilled_impressions', $totals['unfilled_impressions']) }}</td><td class="money">{{ \App\Support\Money::formatMinor($totals['revenue_minor']) }}</td><td>{{ $totals['ecpm_minor'] === null ? 'Unavailable' : \App\Services\Reporting\PerformanceMetrics::display('ecpm_minor', $totals['ecpm_minor']) }}</td>@unless($publisher)<td>{{ \App\Support\Money::formatMinor($totals['publisher_earnings_minor']) }}</td><td>{{ \App\Support\Money::formatMinor($totals['horus_earnings_minor']) }}</td>@endunless</tr></tfoot>@endif
</table></div>
<div class="publisher-report-mobile-rows video-mobile-rows" role="region" aria-label="{{ $caption }}">
@foreach($rows as $row)
<div class="publisher-report-mobile-row"><div class="publisher-report-mobile-row-heading"><span><strong>{{ $label === 'Date' ? \Carbon\CarbonImmutable::parse($row['date'])->format('j M Y') : $row['label'] }}</strong>@if($label === 'Website' && ($row['domain'] ?? null))<small>{{ $row['domain'] }}</small>@endif @if($row['has_estimates'])<small>Estimated</small>@endif</span><span class="publisher-row-earnings"><small>{{ $revenueLabel }}</small><strong>{{ \App\Support\Money::formatMinor($row['revenue_minor']) }} <small>{{ $currency }}</small></strong></span></div>
<dl>@foreach(['impressions' => 'Impressions', 'ecpm_minor' => 'eCPM', 'unfilled_impressions' => 'Unfilled · all sites'] as $key => $metric)<div><dt>{{ $metric }}</dt><dd>{{ $row[$key] === null ? 'Unavailable' : \App\Services\Reporting\PerformanceMetrics::display($key, $row[$key]) }}@if($key === 'ecpm_minor' && $row[$key] !== null) <small>{{ $currency }}</small>@endif</dd></div>@endforeach @unless($publisher)<div><dt>Publisher earnings</dt><dd>{{ \App\Support\Money::formatMinor($row['publisher_earnings_minor']) }} {{ $currency }}</dd></div><div><dt>Horus margin</dt><dd>{{ \App\Support\Money::formatMinor($row['horus_earnings_minor']) }} {{ $currency }}</dd></div>@endunless</dl></div>
@endforeach
</div>
