@extends('layouts.admin')
@section('title',$campaign->name)
@section('heading',$campaign->name)
@section('navigation')<a href="{{ route('admin.campaigns.index') }}">Campaigns</a><span class="active">{{ $campaign->status->value }}</span><a href="{{ route('admin.gam.connections.index') }}">GAM</a>@endsection
@section('content')
<section class="hero"><div><p class="eyebrow">{{ $campaign->public_key }} · {{ $campaign->advertiser->display_name }}</p><h2>{{ $campaign->objective }}</h2><div class="status-row"><span class="pill">{{ $campaign->status->value }}</span><span class="pill">{{ $campaign->pricing_model->value }}</span><span class="pill">{{ $campaign->currency }} {{ number_format($campaign->total_budget_minor/100,2) }}</span><span class="pill">{{ count($preview['plans'] ?? []) }} GAM networks</span></div></div><form method="POST" action="{{ route('admin.advertisers.campaign-review',$campaign->advertiser) }}">@csrf<input type="hidden" name="approved" value="1"><button class="hm-button-secondary">Approve advertiser</button></form></section>
<section class="metric-grid">@foreach([['Objects planned',$preview['estimatedObjects'] ?? 0],['Objects pending',$preview['pendingObjects'] ?? 0],['Impressions',number_format($report['impressions'])],['Clicks',number_format($report['clicks'])],['Spend',$campaign->currency.' '.number_format($report['spend_minor']/100,2)]] as [$label,$value])<article><p class="eyebrow">{{ $label }}</p><strong class="metric-small">{{ $value }}</strong></article>@endforeach</section>
@if($preview['issues'] ?? [])<article class="danger-zone"><h3>Deployment blockers</h3>@foreach($preview['issues'] as $issue)<p class="error">{{ $issue }}</p>@endforeach</article>@endif
<section class="detail-grid"><article><p class="eyebrow">Campaign review</p><h2>Approval and lifecycle</h2>
<div class="status-row">
@if($campaign->status->value==='PENDING_REVIEW')<form method="POST" action="{{ route('admin.campaigns.approve',$campaign) }}">@csrf<button class="hm-button-primary">Approve campaign</button></form><form method="POST" action="{{ route('admin.campaigns.reject',$campaign) }}">@csrf<input class="hm-input" name="reason" placeholder="Rejection reason" required><button class="hm-button-secondary">Reject</button></form>@endif
@if($campaign->status->value==='APPROVED')<form method="POST" action="{{ route('admin.campaigns.schedule',$campaign) }}">@csrf<button class="hm-button-primary">Schedule campaign</button></form>@endif
@if(in_array($campaign->status->value,['SCHEDULED','ACTIVE']))<form method="POST" action="{{ route('admin.campaigns.pause',$campaign) }}">@csrf<button class="hm-button-secondary">Pause all networks</button></form>@endif
@if($campaign->status->value==='PAUSED')<form method="POST" action="{{ route('admin.campaigns.resume',$campaign) }}">@csrf<button class="hm-button-primary">Resume all networks</button></form>@endif
@if(!in_array($campaign->status->value,['COMPLETED','ARCHIVED']))<form method="POST" action="{{ route('admin.campaigns.complete',$campaign) }}">@csrf<button class="hm-button-secondary">End campaign</button></form>@endif
</div>
<form class="form-stack" method="POST" action="{{ route('admin.campaigns.bonus',$campaign) }}">@csrf<h3>Add bonus inventory</h3><label>Bonus units<input class="hm-input" type="number" min="1" name="units" required></label><label>Note<input class="hm-input" name="note" required></label><button class="hm-button-secondary">Add bonus</button></form></article>
<article><p class="eyebrow">GAM deployment</p><h2>Plan and execute</h2><p>External writes are isolated per network and require explicit confirmation.</p><div class="status-row"><form method="POST" action="{{ route('admin.campaigns.gam.dry-run',$campaign) }}">@csrf<button class="hm-button-secondary">Run dry-run</button></form><form method="POST" action="{{ route('admin.campaigns.gam.deploy',$campaign) }}">@csrf<label><input type="checkbox" name="confirm_external_writes" value="1" required> Confirm up to {{ $preview['pendingObjects'] ?? 0 }} GAM writes</label><button class="hm-button-primary">Deploy to GAM</button></form></div><div class="status-row"><form method="POST" action="{{ route('admin.campaigns.gam.synchronize',$campaign) }}">@csrf<button class="hm-button-secondary">Request delivery report</button></form><form method="POST" action="{{ route('admin.campaigns.gam.reconcile',$campaign) }}">@csrf<button class="hm-button-secondary">Detect remote drift</button></form></div></article></section>
<article><p class="eyebrow">Independent remote instances</p><h2>Network deployment plan</h2>@foreach($campaign->networkInstances as $instance)<div class="domain-card"><div><strong>{{ $instance->network_type->value }}</strong><span>{{ $instance->connection->name }} · network {{ $instance->network_code }}</span><div class="status-row"><span class="pill">{{ $instance->status->value }}</span><span class="pill">{{ $instance->completed_objects }}/{{ $instance->planned_objects }} objects</span><span class="pill">{{ $campaign->currency }} {{ number_format($instance->budget_allocated_minor/100,2) }}</span>@if($instance->drift_detected_at)<span class="pill">DRIFT</span>@endif</div>@if($instance->last_error)<p class="error">{{ $instance->last_error }}</p>@endif</div>@if(in_array($instance->status->value,['FAILED','PARTIAL','DRIFTED']))<form method="POST" action="{{ route('admin.campaigns.gam.retry',[$campaign,$instance]) }}">@csrf<label><input type="checkbox" name="confirm_external_writes" value="1" required> Confirm retry</label><button class="hm-button-secondary">Retry this network only</button></form>@endif</div>@endforeach</article>
<section class="detail-grid"><article><p class="eyebrow">Creatives</p><h2>Creative review</h2>@foreach($campaign->creatives as $creative)<div class="domain-card"><div><strong>{{ $creative->name }}</strong><div class="status-row"><span class="pill">{{ $creative->type->value }}</span><span class="pill">{{ $creative->status->value }}</span><span class="pill">{{ $creative->width }}×{{ $creative->height }}</span></div>@if($creative->rejection_reason)<p class="error">{{ $creative->rejection_reason }}</p>@endif</div>@if(in_array($creative->status->value,['PENDING_REVIEW','DRAFT']))<div><form method="POST" action="{{ route('admin.campaigns.creatives.review',[$campaign,$creative]) }}">@csrf<input type="hidden" name="approved" value="1"><button class="hm-button-primary">Approve</button></form><form method="POST" action="{{ route('admin.campaigns.creatives.review',[$campaign,$creative]) }}">@csrf<input type="hidden" name="approved" value="0"><input class="hm-input" name="reason" placeholder="Reason" required><button class="hm-button-secondary">Reject</button></form></div>@endif</div>@endforeach</article>
<article><p class="eyebrow">Targeting</p><h2>Selected inventory</h2>@foreach($campaign->sites as $row)<div class="event"><div><strong>{{ $row->site->display_name }}</strong><br><span>{{ $row->site->publisher->display_name }}</span></div><span>{{ $row->site->serving_mode->value }}</span></div>@endforeach<p>{{ $campaign->placements->count() ? $campaign->placements->count().' explicit placements' : 'All active placements' }}</p><h3>Audience</h3>@foreach($campaign->targets as $target)<p><strong>{{ $target->dimension }}</strong>: {{ implode(', ',$target->values) }}</p>@endforeach</article></section>
<article><p class="eyebrow">Audit</p><h2>Approval and deployment history</h2>@foreach($campaign->approvalLogs->sortByDesc('created_at')->take(30) as $log)<div class="event"><div><strong>{{ $log->action }}</strong><br><span>{{ $log->actor?->name ?? 'System' }} · {{ $log->reason }}</span></div><span>{{ $log->created_at }}</span></div>@endforeach</article>
@endsection
