@extends('layouts.admin')
@section('title', 'Production operations')
@section('heading', 'Production operations')
@section('navigation')
<a href="{{ route('dashboard') }}">Overview</a><a class="active" href="{{ route('admin.operations.index') }}">Operations</a>@if(auth()->user()->hasPermission('reporting.admin.view'))<a href="{{ route('admin.reporting.index') }}">Reporting</a>@endif @if(auth()->user()->hasPermission('sites.view'))<a href="{{ route('admin.sites.index') }}">Websites</a>@endif
@endsection
@section('content')
<section class="split-grid">
<article><h2>Platform controls</h2><p class="muted">Every change requires the administrator password and is audited. Browser controls are atomically published to <code>configs/control.json</code>.</p>
@foreach($controls as $key => $enabled)
<form method="POST" action="{{ route('admin.operations.controls.update') }}" class="event">@csrf
<input type="hidden" name="key" value="{{ $key }}"><input type="hidden" name="enabled" value="{{ $enabled ? 0 : 1 }}">
<div><strong>{{ str($key)->replace('_',' ')->title() }}</strong><span>{{ $enabled ? 'Enabled' : 'Disabled' }}</span></div>
<input name="reason" placeholder="Reason" required maxlength="2000"><input type="password" name="current_password" placeholder="Current password" required>
<button class="{{ $enabled ? 'danger' : '' }}">{{ $enabled ? 'Disable' : 'Enable' }}</button></form>
@endforeach</article>
<article><h2>Cron heartbeat</h2>@forelse($heartbeats as $heartbeat)<div class="event"><strong>{{ $heartbeat->name }}</strong><span>{{ $heartbeat->status }} · {{ optional($heartbeat->last_completed_at)->diffForHumans() ?: 'never completed' }}</span></div>@empty<p class="muted">No heartbeat recorded. Configure the scheduler cron before production.</p>@endforelse</article>
</section>
<section class="split-grid"><article><h2>Failed database jobs</h2>@forelse($failedJobs as $job)<div class="event"><div><strong>{{ $job->uuid }}</strong><span>{{ $job->queue }} · {{ $job->failed_at }}</span></div><form method="POST" action="{{ route('admin.operations.failed-jobs.retry',$job->uuid) }}">@csrf<input type="password" name="current_password" placeholder="Password" required><button>Retry</button></form><form method="POST" action="{{ route('admin.operations.failed-jobs.forget',$job->uuid) }}">@csrf @method('DELETE')<input type="password" name="current_password" placeholder="Password" required><button class="danger">Forget</button></form></div>@empty<p class="muted">No failed jobs.</p>@endforelse</article>
<article><h2>Failed report imports</h2>@forelse($failedImports as $import)<div class="event"><strong>{{ $import->connection?->name ?: $import->connection?->source?->name ?: 'Source' }}</strong><span>{{ $import->error_message ?: 'Failed' }} · attempts {{ $import->attempt_count }}</span>@if(Route::has('admin.reporting.import.retry'))<form method="POST" action="{{ route('admin.reporting.import.retry',$import) }}">@csrf<button>Retry import</button></form>@endif</div>@empty<p class="muted">No failed imports.</p>@endforelse</article></section>
<section class="split-grid"><article><h2>Loader rollback</h2>@forelse($loaderReleases as $release)<form method="POST" action="{{ route('admin.operations.loaders.rollback',$release) }}" class="event">@csrf<div><strong>{{ $release->version }}</strong><span>{{ $release->is_active ? 'Active' : 'Available' }} · {{ $release->checksum }}</span></div><input name="reason" required placeholder="Rollback reason"><label><input type="checkbox" name="apply_to_all_sites" value="1"> Apply to all sites</label><input type="password" name="current_password" required placeholder="Current password"><button>Activate</button></form>@empty<p class="muted">No loader releases.</p>@endforelse</article>
<article><h2>Configuration rollback</h2>@forelse($configVersions as $version)<form method="POST" action="{{ route('admin.operations.configs.rollback',$version) }}" class="event">@csrf<div><strong>{{ $version->site?->display_name }} v{{ $version->version }}</strong><span>{{ $version->checksum }}</span></div><input name="reason" required placeholder="Rollback reason"><input type="password" name="current_password" required placeholder="Current password"><button>Rollback via new version</button></form>@empty<p class="muted">No production versions.</p>@endforelse</article></section>
<section class="split-grid"><article><h2>Website kill switches</h2>@forelse($sites as $site)<form method="POST" action="{{ route('admin.operations.sites.update',$site) }}" class="event">@csrf<input type="hidden" name="enabled" value="{{ $site->siteConfig?->immediate_pause ? 1 : 0 }}"><div><strong>{{ $site->display_name }}</strong><span>{{ $site->siteConfig?->immediate_pause ? 'Paused' : 'Serving' }} · {{ $site->serving_mode->value }}</span></div><input name="reason" required placeholder="Reason"><input type="password" name="current_password" required placeholder="Current password"><button class="{{ $site->siteConfig?->immediate_pause ? '' : 'danger' }}">{{ $site->siteConfig?->immediate_pause ? 'Resume' : 'Pause now' }}</button></form>@empty<p class="muted">No websites.</p>@endforelse</article>
<article><h2>Placement kill switches</h2>@forelse($placements as $placement)<form method="POST" action="{{ route('admin.operations.placements.update',$placement) }}" class="event">@csrf<input type="hidden" name="enabled" value="{{ $placement->status->value === 'ACTIVE' ? 0 : 1 }}"><div><strong>{{ $placement->site?->display_name }} / {{ $placement->code }}</strong><span>{{ $placement->status->value }}</span></div><input name="reason" required placeholder="Reason"><input type="password" name="current_password" required placeholder="Current password"><button class="{{ $placement->status->value === 'ACTIVE' ? 'danger' : '' }}">{{ $placement->status->value === 'ACTIVE' ? 'Pause' : 'Enable' }}</button></form>@empty<p class="muted">No placements.</p>@endforelse</article></section>
<section><h2>GAM connector kill switches</h2><p class="muted">These emergency controls do not remove or block the HORUS_GAM architecture. They temporarily stop a selected connector while preserving its configuration.</p>@forelse($gamConnections as $connection)<form method="POST" action="{{ route('admin.operations.gam-connections.update',$connection) }}" class="event">@csrf<input type="hidden" name="enabled" value="{{ $connection->is_enabled ? 0 : 1 }}"><div><strong>{{ $connection->name }}</strong><span>{{ $connection->type->value }} · {{ $connection->network_code ?: 'network pending' }} · {{ $connection->is_enabled ? 'Enabled' : 'Disabled' }}</span></div><input name="reason" required placeholder="Reason"><input type="password" name="current_password" required placeholder="Current password"><button class="{{ $connection->is_enabled ? 'danger' : '' }}">{{ $connection->is_enabled ? 'Disable' : 'Enable' }}</button></form>@empty<p class="muted">No GAM connections.</p>@endforelse</section>
@endsection
