<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\Admin\AccountStatusController;
use App\Http\Controllers\Admin\AdvertiserController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\ContractController as AdminContractController;
use App\Http\Controllers\Admin\GamConnectionController;
use App\Http\Controllers\Admin\ImpersonationController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\OrganizationController;
use App\Http\Controllers\Admin\PublisherController;
use App\Http\Controllers\Admin\PublisherPaymentProfileController;
use App\Http\Controllers\Admin\RolePermissionController;
use App\Http\Controllers\Admin\SiteConfigController;
use App\Http\Controllers\Admin\SiteController as AdminSiteController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\InvitationController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\Auth\TwoFactorController;
use App\Http\Controllers\BrandingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Publisher\ContractController as PublisherContractController;
use App\Http\Controllers\Publisher\OnboardingController;
use App\Http\Controllers\Publisher\SiteController as PublisherSiteController;
use App\Http\Controllers\Publisher\SiteVerificationController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:login')->name('login.store');
    Route::get('/forgot-password', [PasswordResetController::class, 'request'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'email'])->middleware('throttle:5,1')->name('password.email');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'reset'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'update'])->middleware('throttle:6,1')->name('password.update');
    Route::get('/invitations/{token}', [InvitationController::class, 'show'])->name('invitations.accept.show');
    Route::post('/invitations/{token}', [InvitationController::class, 'accept'])->name('invitations.accept');
    Route::get('/two-factor/challenge', [TwoFactorController::class, 'challenge'])->name('two-factor.challenge');
    Route::post('/two-factor/challenge', [TwoFactorController::class, 'verifyChallenge'])->middleware('throttle:6,1')->name('two-factor.verify');
});

Route::middleware(['auth', 'active'])->group(function (): void {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/verify-email', [EmailVerificationController::class, 'notice'])->name('verification.notice');
    Route::get('/verify-email/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware('signed')->name('verification.verify');
    Route::post('/email/verification-notification', [EmailVerificationController::class, 'send'])->middleware('throttle:6,1')->name('verification.send');
    Route::get('/two-factor/setup', [TwoFactorController::class, 'setup'])->name('two-factor.setup');
    Route::post('/two-factor/confirm', [TwoFactorController::class, 'confirm'])->middleware('throttle:6,1')->name('two-factor.confirm');
    Route::get('/two-factor/recovery-codes', [TwoFactorController::class, 'recoveryCodes'])->name('two-factor.recovery-codes');
    Route::post('/two-factor/recovery-codes', [TwoFactorController::class, 'regenerate'])->name('two-factor.recovery-codes.regenerate');
    Route::delete('/two-factor', [TwoFactorController::class, 'disable'])->name('two-factor.disable');

    Route::middleware(['verified', 'admin.2fa'])->group(function (): void {
        Route::get('/', DashboardController::class)->name('dashboard');
        Route::get('/account/publishers/{publisher}', [AccountController::class, 'publisher'])->name('account.publisher');
        Route::get('/account/advertisers/{advertiser}', [AccountController::class, 'advertiser'])->name('account.advertiser');

        Route::get('/publisher/onboarding/{step}', [OnboardingController::class, 'show'])->whereNumber('step')->middleware('permission:onboarding.manage')->name('publisher.onboarding.show');
        Route::put('/publisher/onboarding/{step}', [OnboardingController::class, 'update'])->whereNumber('step')->middleware('permission:onboarding.manage')->name('publisher.onboarding.update');
        Route::get('/publisher/sites', [PublisherSiteController::class, 'index'])->middleware('permission:sites.view')->name('publisher.sites.index');
        Route::get('/publisher/sites/create', [PublisherSiteController::class, 'create'])->middleware('permission:sites.manage')->name('publisher.sites.create');
        Route::post('/publisher/sites', [PublisherSiteController::class, 'store'])->middleware('permission:sites.manage')->name('publisher.sites.store');
        Route::get('/publisher/sites/{site}', [PublisherSiteController::class, 'show'])->middleware('permission:sites.view')->name('publisher.sites.show');
        Route::get('/publisher/sites/{site}/edit', [PublisherSiteController::class, 'edit'])->middleware('permission:sites.manage')->name('publisher.sites.edit');
        Route::put('/publisher/sites/{site}', [PublisherSiteController::class, 'update'])->middleware('permission:sites.manage')->name('publisher.sites.update');
        Route::post('/publisher/sites/{site}/domains', [PublisherSiteController::class, 'addDomain'])->middleware('permission:sites.manage')->name('publisher.sites.domains.store');
        Route::post('/publisher/sites/{site}/submit', [PublisherSiteController::class, 'submit'])->middleware('permission:sites.manage')->name('publisher.sites.submit');
        Route::post('/publisher/sites/{site}/domains/{domain}/verify', [SiteVerificationController::class, 'verify'])->middleware(['permission:sites.manage', 'throttle:10,1'])->name('publisher.sites.domains.verify');
        Route::get('/publisher/contracts', [PublisherContractController::class, 'index'])->middleware('permission:contracts.view')->name('publisher.contracts.index');
        Route::get('/publisher/contracts/{contract}', [PublisherContractController::class, 'show'])->middleware('permission:contracts.view')->name('publisher.contracts.show');
        Route::get('/publisher/contracts/{contract}/download', [PublisherContractController::class, 'download'])->middleware(['permission:contracts.view', 'throttle:20,1'])->name('publisher.contracts.download');

        Route::get('/admin/invitations/create', [InvitationController::class, 'create'])->middleware('permission:users.invite')->name('admin.invitations.create');
        Route::post('/admin/invitations', [InvitationController::class, 'store'])->middleware('permission:users.invite')->name('admin.invitations.store');
        Route::patch('/admin/users/{user}/activate', [UserController::class, 'activate'])->middleware('permission:users.manage')->name('admin.users.activate');
        Route::patch('/admin/users/{user}/suspend', [UserController::class, 'suspend'])->middleware('permission:users.manage')->name('admin.users.suspend');
        Route::delete('/admin/users/{user}', [UserController::class, 'destroy'])->middleware('permission:users.manage')->name('admin.users.destroy');
        Route::patch('/admin/organizations/{organization}/status', [AccountStatusController::class, 'organization'])->middleware('permission:organizations.manage')->name('admin.organizations.status');
        Route::patch('/admin/publishers/{publisher}/status', [AccountStatusController::class, 'publisher'])->middleware('permission:publishers.manage')->name('admin.publishers.status');
        Route::patch('/admin/advertisers/{advertiser}/status', [AccountStatusController::class, 'advertiser'])->middleware('permission:advertisers.manage')->name('admin.advertisers.status');
        Route::get('/admin/organizations', [OrganizationController::class, 'index'])->middleware('permission:organizations.view')->name('admin.organizations.index');
        Route::get('/admin/organizations/create', [OrganizationController::class, 'create'])->middleware('permission:organizations.manage')->name('admin.organizations.create');
        Route::post('/admin/organizations', [OrganizationController::class, 'store'])->middleware('permission:organizations.manage')->name('admin.organizations.store');
        Route::get('/admin/organizations/{organization}/edit', [OrganizationController::class, 'edit'])->middleware('permission:organizations.manage')->name('admin.organizations.edit');
        Route::put('/admin/organizations/{organization}', [OrganizationController::class, 'update'])->middleware('permission:organizations.manage')->name('admin.organizations.update');
        Route::delete('/admin/organizations/{organization}', [OrganizationController::class, 'destroy'])->middleware('permission:organizations.manage')->name('admin.organizations.destroy');
        Route::get('/admin/publishers', [PublisherController::class, 'index'])->middleware('permission:publishers.view')->name('admin.publishers.index');
        Route::get('/admin/publishers/create', [PublisherController::class, 'create'])->middleware('permission:publishers.manage')->name('admin.publishers.create');
        Route::post('/admin/publishers', [PublisherController::class, 'store'])->middleware('permission:publishers.manage')->name('admin.publishers.store');
        Route::get('/admin/publishers/{publisher}/edit', [PublisherController::class, 'edit'])->middleware('permission:publishers.manage')->name('admin.publishers.edit');
        Route::put('/admin/publishers/{publisher}', [PublisherController::class, 'update'])->middleware('permission:publishers.manage')->name('admin.publishers.update');
        Route::delete('/admin/publishers/{publisher}', [PublisherController::class, 'destroy'])->middleware('permission:publishers.manage')->name('admin.publishers.destroy');
        Route::post('/admin/publishers/{publisher}/review', [PublisherController::class, 'review'])->middleware('permission:publishers.manage')->name('admin.publishers.review');
        Route::get('/admin/publishers/{publisher}/payment-profile', [PublisherPaymentProfileController::class, 'edit'])->middleware('permission:publisher_payments.manage')->name('admin.publishers.payment-profile.edit');
        Route::put('/admin/publishers/{publisher}/payment-profile', [PublisherPaymentProfileController::class, 'update'])->middleware('permission:publisher_payments.manage')->name('admin.publishers.payment-profile.update');
        Route::get('/admin/advertisers', [AdvertiserController::class, 'index'])->middleware('permission:advertisers.view')->name('admin.advertisers.index');
        Route::get('/admin/advertisers/create', [AdvertiserController::class, 'create'])->middleware('permission:advertisers.manage')->name('admin.advertisers.create');
        Route::post('/admin/advertisers', [AdvertiserController::class, 'store'])->middleware('permission:advertisers.manage')->name('admin.advertisers.store');
        Route::get('/admin/advertisers/{advertiser}/edit', [AdvertiserController::class, 'edit'])->middleware('permission:advertisers.manage')->name('admin.advertisers.edit');
        Route::put('/admin/advertisers/{advertiser}', [AdvertiserController::class, 'update'])->middleware('permission:advertisers.manage')->name('admin.advertisers.update');
        Route::delete('/admin/advertisers/{advertiser}', [AdvertiserController::class, 'destroy'])->middleware('permission:advertisers.manage')->name('admin.advertisers.destroy');
        Route::post('/admin/publishers/{publisher}/contacts', [ContactController::class, 'storePublisher'])->middleware('permission:publishers.manage')->name('admin.publishers.contacts.store');
        Route::put('/admin/publishers/{publisher}/contacts/{contact}', [ContactController::class, 'updatePublisher'])->middleware('permission:publishers.manage')->name('admin.publishers.contacts.update');
        Route::delete('/admin/publishers/{publisher}/contacts/{contact}', [ContactController::class, 'destroyPublisher'])->middleware('permission:publishers.manage')->name('admin.publishers.contacts.destroy');
        Route::post('/admin/advertisers/{advertiser}/contacts', [ContactController::class, 'storeAdvertiser'])->middleware('permission:advertisers.manage')->name('admin.advertisers.contacts.store');
        Route::put('/admin/advertisers/{advertiser}/contacts/{contact}', [ContactController::class, 'updateAdvertiser'])->middleware('permission:advertisers.manage')->name('admin.advertisers.contacts.update');
        Route::delete('/admin/advertisers/{advertiser}/contacts/{contact}', [ContactController::class, 'destroyAdvertiser'])->middleware('permission:advertisers.manage')->name('admin.advertisers.contacts.destroy');

        Route::get('/admin/gam/connections', [GamConnectionController::class, 'index'])->middleware('permission:gam.connections.view')->name('admin.gam.connections.index');
        Route::get('/admin/gam/connections/create', [GamConnectionController::class, 'create'])->middleware('permission:gam.connections.manage')->name('admin.gam.connections.create');
        Route::post('/admin/gam/connections', [GamConnectionController::class, 'store'])->middleware('permission:gam.connections.manage')->name('admin.gam.connections.store');
        Route::get('/admin/gam/connections/{gamConnection}', [GamConnectionController::class, 'show'])->middleware('permission:gam.connections.view')->name('admin.gam.connections.show');
        Route::get('/admin/gam/connections/{gamConnection}/edit', [GamConnectionController::class, 'edit'])->middleware('permission:gam.connections.manage')->name('admin.gam.connections.edit');
        Route::put('/admin/gam/connections/{gamConnection}', [GamConnectionController::class, 'update'])->middleware('permission:gam.connections.manage')->name('admin.gam.connections.update');
        Route::post('/admin/gam/connections/{gamConnection}/test', [GamConnectionController::class, 'test'])->middleware(['permission:gam.connections.test', 'throttle:10,1'])->name('admin.gam.connections.test');
        Route::post('/admin/gam/connections/{gamConnection}/primary', [GamConnectionController::class, 'primary'])->middleware('permission:gam.connections.manage')->name('admin.gam.connections.primary');
        Route::post('/admin/gam/connections/{gamConnection}/assign-site', [GamConnectionController::class, 'assignSite'])->middleware('permission:gam.connections.assign')->name('admin.gam.connections.assign-site');

        Route::get('/admin/sites', [AdminSiteController::class, 'index'])->middleware('permission:sites.view')->name('admin.sites.index');
        Route::get('/admin/sites/{site}', [AdminSiteController::class, 'show'])->middleware('permission:sites.view')->name('admin.sites.show');
        Route::get('/admin/sites/{site}/inventory', [InventoryController::class, 'index'])->middleware('permission:inventory.view')->name('admin.sites.inventory.index');
        Route::post('/admin/sites/{site}/inventory/ad-units', [InventoryController::class, 'storeAdUnit'])->middleware('permission:inventory.manage')->name('admin.sites.inventory.ad-units.store');
        Route::post('/admin/sites/{site}/inventory/ad-units/{adUnit}/sync', [InventoryController::class, 'syncAdUnit'])->middleware('permission:inventory.sync')->name('admin.sites.inventory.ad-units.sync');
        Route::post('/admin/sites/{site}/inventory/ad-units/{adUnit}/resync', [InventoryController::class, 'resyncAdUnit'])->middleware('permission:inventory.sync')->name('admin.sites.inventory.ad-units.resync');
        Route::post('/admin/sites/{site}/inventory/placements', [InventoryController::class, 'storePlacement'])->middleware('permission:inventory.manage')->name('admin.sites.inventory.placements.store');
        Route::put('/admin/sites/{site}/inventory/placements/{placement}', [InventoryController::class, 'updatePlacement'])->middleware('permission:inventory.manage')->name('admin.sites.inventory.placements.update');
        Route::post('/admin/sites/{site}/inventory/placements-bulk', [InventoryController::class, 'bulkPlacements'])->middleware('permission:inventory.manage')->name('admin.sites.inventory.placements.bulk');
        Route::post('/admin/sites/{site}/inventory/page-targeting', [InventoryController::class, 'pageTargeting'])->middleware('permission:inventory.manage')->name('admin.sites.inventory.page-targeting');
        Route::post('/admin/sites/{site}/inventory/duplicate-layout', [InventoryController::class, 'duplicateLayout'])->middleware('permission:inventory.manage')->name('admin.sites.inventory.duplicate-layout');
        Route::put('/admin/sites/{site}/configuration', [SiteConfigController::class, 'update'])->middleware('permission:configs.manage')->name('admin.sites.config.update');
        Route::get('/admin/sites/{site}/configuration/preview', [SiteConfigController::class, 'preview'])->middleware('permission:configs.view')->name('admin.sites.config.preview');
        Route::post('/admin/sites/{site}/configuration/publish', [SiteConfigController::class, 'publish'])->middleware('permission:configs.publish')->name('admin.sites.config.publish');
        Route::post('/admin/sites/{site}/configuration/versions/{configVersion}/rollback', [SiteConfigController::class, 'rollback'])->middleware('permission:configs.publish')->name('admin.sites.config.rollback');
        Route::post('/admin/sites/{site}/configuration/pause', [SiteConfigController::class, 'pause'])->middleware('permission:configs.publish')->name('admin.sites.config.pause');
        Route::post('/admin/sites/{site}/configuration/resume', [SiteConfigController::class, 'resume'])->middleware('permission:configs.publish')->name('admin.sites.config.resume');
        Route::post('/admin/sites/{site}/approve', [AdminSiteController::class, 'approve'])->middleware('permission:sites.review')->name('admin.sites.approve');
        Route::post('/admin/sites/{site}/reject', [AdminSiteController::class, 'reject'])->middleware('permission:sites.review')->name('admin.sites.reject');
        Route::post('/admin/sites/{site}/activate', [AdminSiteController::class, 'activate'])->middleware('permission:sites.review')->name('admin.sites.activate');
        Route::post('/admin/sites/{site}/suspend', [AdminSiteController::class, 'suspend'])->middleware('permission:sites.review')->name('admin.sites.suspend');
        Route::post('/admin/sites/{site}/reactivate', [AdminSiteController::class, 'reactivate'])->middleware('permission:sites.review')->name('admin.sites.reactivate');
        Route::post('/admin/sites/{site}/archive', [AdminSiteController::class, 'archive'])->middleware('permission:sites.review')->name('admin.sites.archive');
        Route::post('/admin/sites/{site}/serving-mode', [AdminSiteController::class, 'servingMode'])->middleware('permission:sites.serving.manage')->name('admin.sites.serving-mode');
        Route::post('/admin/sites/{site}/revenue-share', [AdminSiteController::class, 'revenueShare'])->middleware('permission:sites.serving.manage')->name('admin.sites.revenue-share');
        Route::post('/admin/sites/{site}/notes', [AdminSiteController::class, 'note'])->middleware('permission:sites.review')->name('admin.sites.notes.store');
        Route::post('/admin/sites/{site}/domains/{domain}/manual-verify', [AdminSiteController::class, 'manualVerify'])->middleware('permission:sites.review')->name('admin.sites.domains.manual-verify');
        Route::post('/admin/sites/{site}/emergency-pause', [AdminSiteController::class, 'emergencyPause'])->middleware('permission:sites.serving.manage')->name('admin.sites.emergency-pause');
        Route::get('/admin/publishers/{publisher}/contracts', [AdminContractController::class, 'index'])->middleware('permission:contracts.view')->name('admin.publishers.contracts.index');
        Route::get('/admin/publishers/{publisher}/contracts/create', [AdminContractController::class, 'create'])->middleware('permission:contracts.manage')->name('admin.publishers.contracts.create');
        Route::post('/admin/publishers/{publisher}/contracts', [AdminContractController::class, 'store'])->middleware('permission:contracts.manage')->name('admin.publishers.contracts.store');
        Route::get('/admin/publishers/{publisher}/contracts/{contract}/edit', [AdminContractController::class, 'edit'])->middleware('permission:contracts.manage')->name('admin.publishers.contracts.edit');
        Route::put('/admin/publishers/{publisher}/contracts/{contract}', [AdminContractController::class, 'update'])->middleware('permission:contracts.manage')->name('admin.publishers.contracts.update');
        Route::post('/admin/publishers/{publisher}/contracts/{contract}/status', [AdminContractController::class, 'status'])->middleware('permission:contracts.manage')->name('admin.publishers.contracts.status');
        Route::post('/admin/publishers/{publisher}/contracts/{contract}/upload', [AdminContractController::class, 'upload'])->middleware('permission:contracts.manage')->name('admin.publishers.contracts.upload');
        Route::get('/admin/publishers/{publisher}/contracts/{contract}/download', [AdminContractController::class, 'download'])->middleware(['permission:contracts.view', 'throttle:20,1'])->name('admin.publishers.contracts.download');
        Route::get('/admin/access', [RolePermissionController::class, 'index'])->middleware('permission:roles.view')->name('admin.roles.index');
        Route::post('/admin/users/{user}/roles', [RolePermissionController::class, 'assignRole'])->middleware('permission:roles.manage')->name('admin.users.roles.assign');
        Route::put('/admin/roles/{role}/permissions', [RolePermissionController::class, 'syncPermissions'])->middleware('permission:roles.manage')->name('admin.roles.permissions.sync');
        Route::post('/admin/impersonate/{user}', [ImpersonationController::class, 'start'])->middleware('permission:users.impersonate')->name('admin.impersonate.start');
        Route::delete('/admin/impersonate', [ImpersonationController::class, 'stop'])->name('admin.impersonate.stop');
        Route::get('/account/branding', [BrandingController::class, 'edit'])->middleware('permission:branding.manage')->name('account.branding.edit');
        Route::put('/account/branding', [BrandingController::class, 'update'])->middleware('permission:branding.manage')->name('account.branding.update');
        Route::get('/admin/organizations/{organization}/branding', [BrandingController::class, 'edit'])->middleware('permission:organizations.manage')->name('admin.organizations.branding.edit');
        Route::put('/admin/organizations/{organization}/branding', [BrandingController::class, 'update'])->middleware('permission:organizations.manage')->name('admin.organizations.branding.update');
    });
});
