@extends('layouts.admin')
@section('title', $site->display_name)
@section('heading', $internal ? 'Website review' : $site->display_name)
@section('navigation')<a href="{{ route('dashboard') }}">Overview</a><a class="active" href="{{ $internal ? route('admin.sites.index') : route('publisher.sites.index') }}">Websites</a>@if($internal)<a href="{{ route('admin.sites.inventory.index', $site) }}">Inventory</a>@else<a href="{{ route('publisher.contracts.index') }}">Contracts</a>@endif @endsection
@section('content')
<section class="detail-grid">
<article><p class="eyebrow">Website</p><h2>{{ $site->display_name }}</h2><p>{{ $site->primary_domain }}</p><div class="status-row"><span class="pill">{{ $site->status->value }}</span><span class="pill">{{ $site->serving_mode->value }}</span></div><dl><dt>Language / country</dt><dd>{{ $site->language }} / {{ $site->country }}</dd><dt>Category</dt><dd>{{ $site->content_category }}</dd><dt>Monthly pageviews / users</dt><dd>{{ number_format($site->estimated_monthly_pageviews) }} / {{ number_format($site->estimated_monthly_users) }}</dd><dt>Revenue share</dt><dd>{{ $site->default_revenue_share_percent }}%</dd></dl>@if($internal)<p><a class="hm-button-primary button-link" href="{{ route('admin.sites.inventory.index', $site) }}">Manage inventory and loader</a></p>@endif</article>
<article><p class="eyebrow">Permanent installation</p><h2>One loader</h2><p class="muted">This code never changes when serving mode or demand configuration changes.</p><code class="installation-code">{{ $site->installationCode() }}</code><p>Installation status: <strong>{{ $site->status === \App\Enums\SiteStatus::Active ? 'Active' : 'Configuration pending' }}</strong></p></article>
</section>

<article><div class="section-heading"><div><p class="eyebrow">Authorized domains</p><h2>Ownership verification</h2></div></div>
@foreach($site->domains as $domain)<div class="domain-card"><div><strong>{{ $domain->domain }}</strong> @if($domain->is_primary)<span class="pill">Primary</span>@endif <span class="pill">{{ $domain->verification_status }}</span></div>
<details><summary>Verification instructions</summary><ul><li>Meta tag: <code>&lt;meta name="horus-site-verification" content="{{ $domain->verification_token }}"&gt;</code></li><li>Text file: publish <code>{{ $domain->verification_token }}</code> at <code>/.well-known/horus-verification.txt</code></li><li>DNS TXT: host <code>_horus-verify.{{ $domain->domain }}</code>, value <code>horus-site-verification={{ $domain->verification_token }}</code></li></ul></details>
@if(!$internal && auth()->user()->hasPermission('sites.manage'))<form method="POST" action="{{ route('publisher.sites.domains.verify', [$site, $domain]) }}" class="inline-form">@csrf<select class="hm-input" name="method"><option>META_TAG</option><option>TEXT_FILE</option><option>DNS_TXT</option></select><button class="hm-button-secondary">Verify now</button></form>@endif
@if($internal)<form method="POST" action="{{ route('admin.sites.domains.manual-verify', [$site, $domain]) }}" class="inline-form">@csrf<input class="hm-input" name="reason" placeholder="Manual verification evidence/reason" required><button class="hm-button-secondary">Verify manually</button></form>@endif
</div>@endforeach
@if(!$internal && auth()->user()->hasPermission('sites.manage'))<form method="POST" action="{{ route('publisher.sites.domains.store', $site) }}" class="inline-form">@csrf<input class="hm-input" name="domain" placeholder="additional.example.com" required><button class="hm-button-secondary">Add authorized domain</button></form>@endif
</article>

@if(!$internal)
<article><p class="eyebrow">Review</p><h2>Submission status</h2>@forelse($site->reviews->sortByDesc('created_at') as $review)<div class="event"><div><strong>{{ $review->decision }}</strong><p>{{ $review->publisher_message }}</p></div><span>{{ $review->created_at }}</span></div>@empty<p class="muted">Not submitted yet.</p>@endforelse
@if(auth()->user()->hasPermission('sites.manage') && in_array($site->status, [\App\Enums\SiteStatus::Draft, \App\Enums\SiteStatus::PendingVerification, \App\Enums\SiteStatus::Rejected], true))<form method="POST" action="{{ route('publisher.sites.submit', $site) }}">@csrf<button class="hm-button-primary">Submit for review</button></form>@endif</article>
@else
<section class="detail-grid">
<article><h2>Review decision</h2>@if($site->status === \App\Enums\SiteStatus::PendingReview)<form method="POST" action="{{ route('admin.sites.approve', $site) }}" class="form-stack">@csrf<textarea class="hm-input" name="publisher_message" placeholder="Message to publisher"></textarea><textarea class="hm-input" name="internal_reason" placeholder="Internal reason"></textarea><button class="hm-button-primary">Approve website</button></form><form method="POST" action="{{ route('admin.sites.reject', $site) }}" class="form-stack danger-zone">@csrf<textarea class="hm-input" name="publisher_message" placeholder="Required publisher explanation" required></textarea><textarea class="hm-input" name="internal_reason" placeholder="Required internal reason" required></textarea><button class="hm-button-danger">Reject website</button></form>@elseif($site->status === \App\Enums\SiteStatus::Approved)<form method="POST" action="{{ route('admin.sites.activate', $site) }}" class="inline-form">@csrf<input class="hm-input" name="reason" placeholder="Activation note"><button class="hm-button-primary">Activate</button></form>@elseif($site->status === \App\Enums\SiteStatus::Suspended)<form method="POST" action="{{ route('admin.sites.reactivate', $site) }}" class="inline-form">@csrf<input class="hm-input" name="reason" placeholder="Required reason" required><button class="hm-button-primary">Reactivate</button></form>@endif @if(in_array($site->status, [\App\Enums\SiteStatus::Approved, \App\Enums\SiteStatus::Active, \App\Enums\SiteStatus::Suspended, \App\Enums\SiteStatus::Rejected], true))<form method="POST" action="{{ route('admin.sites.archive', $site) }}" class="inline-form danger-zone">@csrf<input class="hm-input" name="reason" placeholder="Archive reason" required><button class="hm-button-danger">Archive website</button></form>@endif</article>
<article><h2>Serving controls</h2><form method="POST" action="{{ route('admin.sites.serving-mode', $site) }}" class="form-stack">@csrf<select class="hm-input" name="serving_mode">@foreach(\App\Enums\ServingMode::cases() as $mode)<option value="{{ $mode->value }}" @selected($site->serving_mode === $mode)>{{ $mode->value }}</option>@endforeach</select><input class="hm-input" name="reason" placeholder="Required reason" required><button class="hm-button-secondary">Change serving mode</button></form><form method="POST" action="{{ route('admin.sites.revenue-share', $site) }}" class="form-stack">@csrf<input class="hm-input" type="number" min="0" max="100" step=".01" name="revenue_share_percent" value="{{ $site->default_revenue_share_percent }}" required><input class="hm-input" name="reason" placeholder="Required reason" required><button class="hm-button-secondary">Change revenue share</button></form><form method="POST" action="{{ route('admin.sites.emergency-pause', $site) }}" class="form-stack danger-zone">@csrf<input class="hm-input" name="reason" placeholder="Emergency reason" required><button class="hm-button-danger">Emergency pause</button></form></article>
</section>
<article><h2>Internal notes</h2><form method="POST" action="{{ route('admin.sites.notes.store', $site) }}" class="inline-form">@csrf<textarea class="hm-input" name="note" placeholder="Horus Media only" required></textarea><button class="hm-button-secondary">Add note</button></form>@foreach($site->notes->sortByDesc('created_at') as $note)<div class="event"><p>{{ $note->note }}</p><span>{{ $note->created_at }}</span></div>@endforeach</article>
<article><h2>Complete history</h2><h3>Status</h3>@foreach($site->statusHistory->sortByDesc('created_at') as $item)<div class="event"><strong>{{ $item->previous_status?->value ?? 'CREATED' }} → {{ $item->new_status->value }}</strong><span>{{ $item->created_at }} · {{ $item->reason }}</span></div>@endforeach<h3>Serving mode</h3>@foreach($site->servingModeChanges->sortByDesc('created_at') as $item)<div class="event"><strong>{{ $item->previous_mode?->value ?? 'NONE' }} → {{ $item->new_mode->value }}</strong><span>{{ $item->created_at }} · {{ $item->reason }}</span></div>@endforeach<h3>Reviews</h3>@foreach($site->reviews->sortByDesc('created_at') as $review)<div class="event"><strong>{{ $review->decision }}</strong><span>{{ $review->reviewed_at ?: $review->submitted_at }} · {{ $review->internal_reason }}</span></div>@endforeach<h3>Verification attempts</h3>@foreach($site->verifications->sortByDesc('created_at') as $verification)<div class="event"><strong>{{ $verification->method->value }} · {{ $verification->status }}</strong><span>{{ $verification->attempted_at }} · {{ $verification->failure_reason }}</span></div>@endforeach</article>
@endif
@endsection
