@extends('layouts.admin')
@section('title', 'Advertiser reporting')
@section('heading', 'Campaign delivery and cost')
@section('navigation')<a href="{{ route('dashboard') }}">Overview</a><a href="{{ route('advertiser.campaigns.index') }}">Campaigns</a><a class="active" href="{{ route('advertiser.reporting.index') }}">Reports</a>@endsection
@section('content')
<section class="hero"><div><p class="eyebrow">{{ $advertiser->display_name }}</p><h2>Unified campaign reporting</h2><p>Campaign delivery imported from Horus GAM and any explicitly selected GAM connection.</p></div></section>
<section class="metric-grid"><article><p class="eyebrow">Impressions</p><strong class="metric">{{ number_format($summary['impressions']) }}</strong></article><article><p class="eyebrow">Clicks</p><strong class="metric">{{ number_format($summary['clicks']) }}</strong></article><article><p class="eyebrow">CTR</p><strong class="metric">{{ number_format($summary['ctr_bp']/100,2) }}%</strong></article><article><p class="eyebrow">Spend</p><strong class="metric">{{ number_format($summary['spend_minor']/100,2) }}</strong></article><article><p class="eyebrow">Remaining budget</p><strong class="metric">{{ number_format($summary['remaining_budget_minor']/100,2) }}</strong></article></section>
<article><h2>Campaign delivery</h2>@forelse($summary['campaigns'] as $campaign)<div class="event"><div><strong>{{ $campaign['campaign'] }}</strong><br><span>{{ number_format($campaign['impressions']) }} impressions · {{ number_format($campaign['clicks']) }} clicks · {{ number_format($campaign['ctr_bp']/100,2) }}% CTR</span></div><span>{{ number_format($campaign['spend_minor']/100,2) }}</span></div>@empty<p class="muted">No finalized campaign delivery has been imported.</p>@endforelse</article>
<article><h2>Invoices</h2>@forelse($summary['invoices'] as $invoice)<div class="event"><div><strong>{{ $invoice->invoice_number }}</strong><br><span>{{ $invoice->due_on }} · balance {{ number_format($invoice->balance_due_minor/100,2) }} {{ $invoice->currency }}</span></div><span class="pill">{{ $invoice->status->value }}</span></div>@empty<p class="muted">No invoices.</p>@endforelse</article>
@endsection
