@extends('layouts.admin')
@section('title', 'Publisher reporting')
@section('heading', 'Revenue reports and payments')
@section('content')
<section class="hero"><div><p class="eyebrow">{{ $publisher->display_name }}</p><h2>Unified publisher earnings</h2><p>Finalized earnings from Horus GAM and approved alternative demand sources, without exposing other publishers.</p></div></section>
<section class="metric-grid"><article><p class="eyebrow">Impressions</p><strong class="metric">{{ number_format($summary['impressions']) }}</strong></article><article><p class="eyebrow">Revenue</p><strong class="metric">{{ number_format($summary['revenue_minor']/100,2) }}</strong></article><article><p class="eyebrow">eCPM</p><strong class="metric">{{ number_format($summary['ecpm_micros']/1000000,4) }}</strong></article><article><p class="eyebrow">Payment balance</p><strong class="metric">{{ number_format($summary['payment_balance_minor']/100,2) }}</strong></article></section>
<section class="split-grid"><article><h2>Websites</h2>@forelse($summary['websites'] as $row)<div class="event"><strong>{{ $row['label'] }}</strong><span>{{ number_format($row['publisher_earnings_minor']/100,2) }}</span></div>@empty<p class="muted">No finalized reports.</p>@endforelse</article><article><h2>Placements</h2>@forelse($summary['placements'] as $row)<div class="event"><strong>{{ $row['label'] }}</strong><span>{{ number_format($row['impressions']) }}</span></div>@empty<p class="muted">No finalized reports.</p>@endforelse</article></section>
<article><h2>Statements</h2>@forelse($summary['statements'] as $statement)<div class="event"><div><strong><a href="{{ route('publisher.reporting.statements.show',$statement) }}">{{ $statement->statement_number }}</a></strong><br><span>{{ $statement->period->period_key }} · {{ number_format($statement->balance_due_minor/100,2) }} {{ $statement->currency }}</span></div><span class="pill">{{ $statement->status->value }}</span></div>@empty<p class="muted">Statements appear after monthly closing.</p>@endforelse</article>
@endsection
