@extends('layouts.admin')
@section('title', $statement->statement_number)
@section('heading', 'Publisher statement')
@section('content')
@if(auth()->user()->hasPermission('finance.operations.view'))@include('admin.finance._tabs')@endif
@php($csvRoute = auth()->user()->hasPermission('finance.publisher.view') ? 'admin.finance.statements.csv' : 'admin.reporting.statements.csv')
<section class="hero"><div><p class="eyebrow">{{ $statement->statement_number }}</p><h2>{{ $statement->publisher->display_name }}</h2><p>{{ $statement->period->period_key }} · {{ $statement->currency }} · Snapshot {{ $statement->snapshot_hash }}</p></div><a class="hm-button-primary button-link" href="{{ route($csvRoute,$statement) }}">Export CSV</a></section>
<section class="metric-grid">@foreach ([['Gross',$statement->gross_revenue_minor],['Deductions',$statement->deductions_minor],['Net',$statement->net_revenue_minor],['Publisher earnings',$statement->publisher_earnings_minor],['Opening balance',$statement->opening_balance_minor],['Paid',$statement->paid_minor],['Balance due',$statement->balance_due_minor]] as [$label,$minor])<article><p class="eyebrow">{{ $label }}</p><strong class="metric">{{ \App\Support\Money::formatMinor((int) $minor) }} {{ $statement->currency }}</strong></article>@endforeach</section>
<article><h2>Statement lines</h2>@foreach($statement->line_items as $line)<div class="event"><div><strong>{{ $line['source'] ?? 'SOURCE' }} · {{ $line['site'] ?? ($line['description'] ?? 'All inventory') }}</strong><br><span>{{ number_format($line['impressions'] ?? 0) }} impressions</span></div><span>{{ \App\Support\Money::formatMinor((int) ($line['publisher_earnings_minor'] ?? 0)) }}</span></div>@endforeach</article>
<article><h2>Payments</h2>@forelse($statement->payments as $payment)<div class="event"><div><strong>{{ $payment->payment_number }}</strong><br><span>Requested {{ \App\Support\Money::formatMinor((int) $payment->amount_minor) }} · Settled {{ \App\Support\Money::formatMinor((int) $payment->settled_amount_minor) }}</span>@foreach($payment->settlements as $settlement)<br><span>{{ $settlement->settlement_reference }} · {{ \App\Support\Money::formatMinor((int) $settlement->amount_minor) }}</span>@endforeach</div><x-status-badge :status="$payment->status" /></div>@empty<p class="muted">No payments recorded.</p>@endforelse</article>
@endsection
