@extends('layouts.admin')
@section('title', 'Publisher onboarding')
@section('heading', 'Publisher onboarding')
@section('navigation')<a href="{{ route('dashboard') }}">Overview</a><a class="active" href="{{ route('publisher.onboarding.show', $publisher->onboarding_step) }}">Onboarding</a><a href="{{ route('publisher.sites.index') }}">Websites</a><a href="{{ route('publisher.contracts.index') }}">Contracts</a>@endsection
@section('content')
<ol class="wizard-steps">@foreach([1=>'Company',2=>'Payment',3=>'Contract',4=>'Website',5=>'Verification',6=>'Placements',7=>'Submit'] as $number=>$label)<li class="{{ $number === $step ? 'active' : ($number < $publisher->onboarding_step ? 'complete' : '') }}"><a href="{{ route('publisher.onboarding.show', $number) }}"><span>{{ $number }}</span>{{ $label }}</a></li>@endforeach</ol>
<article class="wizard-card"><form method="POST" action="{{ route('publisher.onboarding.update', $step) }}" class="form-grid">@csrf @method('PUT')
@if($step === 1)
<div class="full"><p class="eyebrow">Step 1</p><h2>Company and primary contact</h2></div><label>Legal company name<input class="hm-input" name="legal_name" value="{{ old('legal_name', $publisher->legal_name) }}" required></label><label>Display name<input class="hm-input" name="display_name" value="{{ old('display_name', $publisher->display_name) }}" required></label><label>Billing email<input class="hm-input" type="email" name="billing_email" value="{{ old('billing_email', $publisher->billing_email) }}" required></label>@php($contact=$publisher->contacts->firstWhere('is_primary', true) ?? $publisher->contacts->first())<label>Contact name<input class="hm-input" name="contact_name" value="{{ old('contact_name', $contact?->name) }}" required></label><label>Contact email<input class="hm-input" type="email" name="contact_email" value="{{ old('contact_email', $contact?->email) }}" required></label><label>Phone<input class="hm-input" name="contact_phone" value="{{ old('contact_phone', $contact?->phone) }}"></label><label>Title<input class="hm-input" name="contact_title" value="{{ old('contact_title', $contact?->title) }}"></label>
@elseif($step === 2)
@php($profile=$publisher->paymentProfile)<div class="full"><p class="eyebrow">Step 2</p><h2>Payment details</h2><p class="muted">Sensitive account and tax references are encrypted at rest and never included in audit payloads. @if($profile?->account_last_four)Saved account: ••••{{ $profile->account_last_four }}; leave replacement fields blank to keep it.@endif</p></div><label>Beneficiary name<input class="hm-input" name="beneficiary_name" value="{{ old('beneficiary_name', $profile?->beneficiary_name) }}" required></label><label>Payment method<select class="hm-input" name="payment_method">@foreach(['BANK_TRANSFER','PAYPAL','WISE','OTHER'] as $method)<option @selected(old('payment_method', $profile?->payment_method)===$method)>{{ $method }}</option>@endforeach</select></label><label>Currency<input class="hm-input" name="currency" value="{{ old('currency', $profile?->currency ?: 'USD') }}" maxlength="3" required></label><label>Country<input class="hm-input" name="country" value="{{ old('country', $profile?->country) }}" maxlength="2" required></label><label class="full">Billing address<input class="hm-input" name="billing_address" value="{{ old('billing_address', $profile?->billing_address) }}"></label><label>Account/payment reference<input class="hm-input" name="account_reference" value="{{ old('account_reference') }}" autocomplete="off" @required(!$profile)></label><label>Routing/SWIFT reference<input class="hm-input" name="routing_reference" value="{{ old('routing_reference') }}" autocomplete="off"></label><label>Tax identifier<input class="hm-input" name="tax_identifier" value="{{ old('tax_identifier') }}" autocomplete="off"></label>
@elseif($step === 3)
<div class="full"><p class="eyebrow">Step 3</p><h2>Commercial agreement</h2></div><label>Contract reference<input class="hm-input" name="contract_reference" value="{{ old('contract_reference', $contract?->contract_reference ?: 'HM-'.$publisher->id) }}" required></label><label>Start date<input class="hm-input" type="date" name="starts_at" value="{{ old('starts_at', $contract?->starts_at?->toDateString()) }}"></label><label>End date<input class="hm-input" type="date" name="ends_at" value="{{ old('ends_at', $contract?->ends_at?->toDateString()) }}"></label><label><input type="hidden" name="auto_renews" value="0"><input type="checkbox" name="auto_renews" value="1" @checked(old('auto_renews', $contract?->auto_renews))> Auto-renewal</label><label>Revenue share %<input class="hm-input" type="number" min="0" max="100" step=".01" name="revenue_share_percent" value="{{ old('revenue_share_percent', $contract?->revenue_share_percent ?: 70) }}" required></label><label>Payment threshold<input class="hm-input" type="number" min="0" step=".01" name="payment_threshold" value="{{ old('payment_threshold', $contract?->payment_threshold ?: 100) }}" required></label><label>Currency<input class="hm-input" name="currency" value="{{ old('currency', $contract?->currency ?: 'USD') }}" maxlength="3" required></label><label>Payment terms<input class="hm-input" name="payment_terms" value="{{ old('payment_terms', $contract?->payment_terms ?: 'NET_30') }}" required></label>
@elseif($step === 4)
<div class="full"><p class="eyebrow">Step 4</p><h2>First website</h2><p class="muted">Serving mode is automatically <strong>HORUS_GAM</strong>. No MCM or publisher GAM connection is required.</p></div><label>Display name<input class="hm-input" name="display_name" value="{{ old('display_name', $site?->display_name) }}" required></label><label>Primary domain<input class="hm-input" name="primary_domain" value="{{ old('primary_domain', $site?->primary_domain) }}" required></label><label>Language<input class="hm-input" name="language" value="{{ old('language', $site?->language ?: 'en') }}" required></label><label>Content category<input class="hm-input" name="content_category" value="{{ old('content_category', $site?->content_category) }}" required></label><label>Country<input class="hm-input" name="country" maxlength="2" value="{{ old('country', $site?->country) }}" required></label><label>Main traffic countries<input class="hm-input" name="main_traffic_countries" value="{{ old('main_traffic_countries', implode(',', $site?->main_traffic_countries ?? [])) }}"></label><label>Monthly pageviews<input class="hm-input" type="number" min="0" name="estimated_monthly_pageviews" value="{{ old('estimated_monthly_pageviews', $site?->estimated_monthly_pageviews ?? 0) }}" required></label><label>Monthly users<input class="hm-input" type="number" min="0" name="estimated_monthly_users" value="{{ old('estimated_monthly_users', $site?->estimated_monthly_users ?? 0) }}" required></label><label>Current providers<input class="hm-input" name="current_monetization_providers" value="{{ old('current_monetization_providers', implode(',', $site?->current_monetization_providers ?? [])) }}"></label><label>Current GAM network code<input class="hm-input" name="current_gam_network_code" value="{{ old('current_gam_network_code', $site?->current_gam_network_code) }}"></label><label>AdSense status<input class="hm-input" name="current_adsense_status" value="{{ old('current_adsense_status', $site?->current_adsense_status) }}"></label><label>AdX status<input class="hm-input" name="current_adx_status" value="{{ old('current_adx_status', $site?->current_adx_status) }}"></label><label>Default revenue share %<input class="hm-input" type="number" min="0" max="100" step=".01" name="default_revenue_share_percent" value="{{ old('default_revenue_share_percent', $site?->default_revenue_share_percent ?: $contract?->revenue_share_percent ?: 70) }}" required></label><label><input type="hidden" name="prebid_enabled" value="0"><input type="checkbox" name="prebid_enabled" value="1" @checked(old('prebid_enabled', $site?->prebid_enabled))> Prebid enabled</label><label><input type="hidden" name="native_demand_enabled" value="0"><input type="checkbox" name="native_demand_enabled" value="1" @checked(old('native_demand_enabled', $site?->native_demand_enabled))> Native demand enabled</label>
@elseif($step === 5)
<div class="full"><p class="eyebrow">Step 5</p><h2>Domain verification</h2><p class="muted">Choose any automated method now, or continue and let an administrator verify manually. Verification does not block selection of HORUS_GAM.</p></div>@forelse($site?->domains ?? [] as $domain)<div class="full domain-card"><strong>{{ $domain->domain }}</strong><span class="pill">{{ $domain->verification_status }}</span><ul><li>Meta: <code>&lt;meta name="horus-site-verification" content="{{ $domain->verification_token }}"&gt;</code></li><li>File: <code>/.well-known/horus-verification.txt</code> = <code>{{ $domain->verification_token }}</code></li><li>DNS: <code>_horus-verify.{{ $domain->domain }}</code> = <code>horus-site-verification={{ $domain->verification_token }}</code></li></ul><a class="text-link" href="{{ route('publisher.sites.show', $site) }}">Run verification check</a></div>@empty<p class="full error">Complete the website step first.</p>@endforelse
@elseif($step === 6)
<div class="full"><p class="eyebrow">Step 6</p><h2>Ad placement planning</h2><p class="muted">This records the plan only. It does not create ad units or call GAM.</p></div><label class="full">Planned formats<input class="hm-input" name="placement_formats" value="{{ old('placement_formats', implode(',', $site?->servingSettings?->placement_plan['formats'] ?? [])) }}" placeholder="Leaderboard,In-article,Sidebar,Sticky" required></label><label class="full">Planning notes<textarea class="hm-input" name="placement_notes" rows="6">{{ old('placement_notes', $site?->servingSettings?->placement_plan['notes'] ?? '') }}</textarea></label>
@else
<div class="full"><p class="eyebrow">Step 7</p><h2>Final submission</h2><p>Review your company, payment profile, contract, website, verification state, and placement plan before submitting.</p><div class="summary-grid"><div><strong>Publisher</strong><span>{{ $publisher->display_name }}</span></div><div><strong>Contract</strong><span>{{ $contract?->contract_reference }} · {{ $contract?->revenue_share_percent }}%</span></div><div><strong>Website</strong><span>{{ $site?->display_name }} · {{ $site?->primary_domain }}</span></div><div><strong>Serving mode</strong><span>{{ $site?->serving_mode?->value ?: 'HORUS_GAM' }}</span></div></div></div><label class="full"><input type="checkbox" name="confirm" value="1" required> I confirm that the submitted information is accurate.</label>
@endif
<div class="full wizard-actions">@if($step > 1)<a class="hm-button-secondary" href="{{ route('publisher.onboarding.show', $step - 1) }}">Back</a>@endif<button class="hm-button-primary">{{ $step === 7 ? 'Submit onboarding' : 'Save and continue' }}</button></div>
</form></article>
@endsection
