from pathlib import Path

sections = {
    'README.md': '''\n## GAM-less controlled pilot baseline (Task 20)\n\nThe multi-engine program is now hardened for a controlled GAM-less pilot. The\nrelease-gated architecture is still one permanent Horus Loader with three\nindependent engines: `GAM`, `Prebid (GAM_BRIDGE or STANDALONE)`, and `Direct JS`.\n`HORUS_DIRECT` may be production-healthy with standalone Prebid and/or Direct JS\nwithout a GAM connection. See `docs/PILOT_RUNBOOK.md` for PILOT A-E and provider\nactivation gates. OneTag is an optional pinned Prebid adapter; ExoClick has a\nreviewed asynchronous Direct JS recipe; Adsterra remains operator-tag-driven\nthrough the generic reviewed importer rather than a guessed hard-coded recipe.\n''',
    'docs/PRODUCT.md': '''\n## Task 20 controlled-pilot product state\n\nThe supported pilot combinations are: standalone Prebid only; Direct JS only;\nstandalone Prebid plus Direct JS on different placements; GAM plus Prebid\n`GAM_BRIDGE`; and GAM plus bridge Prebid plus an independent Direct JS placement.\nNo combination introduces a Prebid-vs-Direct global auction or automatic\nwaterfall. `AD_SERVING` stops all engines; GAM, PREBID and DIRECT_JS controls\nisolate only their own paths.\n''',
    'docs/ARCHITECTURE.md': '''\n## Task 20 final serving topology\n\n```text\nHorus Loader\n├── GAM -> GPT -> selected GAM connection\n├── Prebid -> STANDALONE direct banner render | GAM_BRIDGE -> GPT/GAM\n└── Direct JS -> reviewed structured provider recipe | isolated custom iframe\n```\n\nThe Loader does not load GPT when no GAM-owned placement exists, does not load\nPrebid when no Prebid placement is active, and does not load a Direct provider\nscript when no Direct placement is active. Shared Direct provider scripts are\ndeduplicated while independent placements initialize independently. Renderer\nownership remains per physical placement and conflicts fail closed.\n''',
    'docs/PREBID_ARCHITECTURE.md': '''\n## Task 20 pilot adapter baseline\n\nThe pinned Prebid.js build remains version `11.14.0` and now includes the\noptional `onetagBidAdapter`. OneTag uses the normal bidder -> account -> site ->\nplacement mapping workflow and requires an operator/provider-supplied `pubId`;\nHorus seeds no publisher identifier. Standalone rendering remains banner-only\nand does not load GPT/GAM. GAM Bridge remains unchanged and GAM remains the\nfinal decision point for bridge demand.\n''',
    'docs/PREBID_OPERATIONS.md': '''\n## Task 20 OneTag operations\n\nOneTag is available, not mandatory. Create/enable the OneTag bidder account only\nafter receiving the public `pubId` from OneTag, map it through the existing\nPrebid controls, preview the resulting static configuration, and verify reporting\nthrough an approved aggregated provider import. Missing required public values\nfail closed; credentials are never published.\n''',
    'docs/DIRECT_DEMAND_ENGINE.md': '''\n## Task 20 provider-readiness additions\n\nExoClick asynchronous banner tags are representable as a trusted structured\nrecipe: approved external loader, provider-issued `<ins>` container/class,\n`data-zoneid`, and the documented `AdProvider.push({serve:{}})` queue action.\nHorus never invents the zone ID or provider class. Unapproved origins or altered\ninline actions are rejected.\n\nAdsterra remains on the generic paste -> parse -> review path because the public\nprovider guidance instructs publishers to copy the account-issued script and\ndoes not establish one invariant public tag host/schema suitable for hard-coded\ntrust. If a supplied tag cannot be represented structurally, it must use the\nexisting isolated Custom Third Party mode or fail closed.\n\nTask 20 also removes a failed Direct candidate's container before trying the\nnext provider, preventing a late provider render from coexisting with a winning\nfallback container.\n''',
    'docs/DIRECT_DEMAND_OPERATIONS.md': '''\n## Task 20 pilot operations\n\nFor ExoClick, import the exact provider-issued asynchronous tag and review the\ndetected official script origin, `<ins>` container/class, public `data-zoneid`,\nand trusted serve action before approval. For Adsterra, import the actual tag\nreceived by the operator; do not create a network origin or zone from memory.\nDirect provider failure is placement-local and never steals a Prebid/GAM surface.\n''',
    'docs/NATIVE_NETWORKS.md': '''\n## Direct Demand compatibility note\n\nThe historical Native/Alternative Demand domain is retained for compatibility,\nbut the product surface is now Direct Demand. Existing native networks, accounts,\nwidgets, ads.txt records, reports and history remain valid. Task 20 does not\ncreate a second native domain.\n''',
    'docs/MONETIZATION_READINESS.md': '''\n## Task 20 pilot readiness\n\nA `HORUS_DIRECT` site can be overall ACTIVE with healthy standalone Prebid,\nhealthy Direct Monetization, or both; optional GAM is `NOT_CONFIGURED`, not an\nerror. A GAM-required site still requires a healthy GAM path. Pilot readiness\nalso requires renderer-conflict safety, approved tag recipes, source-aware\naggregated reporting, no secret leakage, and successful release validation.\n''',
    'docs/PILOT_RUNBOOK.md': '''\n## GAM-less and regression pilot profiles (Task 20)\n\nUse the smallest profile that proves the intended deployment; do not configure a\nfake GAM connection. All IDs below are deployment-time provider values and must\nnever be copied from tests.\n\n- **PILOT A — Standalone Prebid only:** `HORUS_DIRECT`, GAM absent, one approved\n  banner placement owned by `PREBID_STANDALONE`. Verify no GPT request.\n- **PILOT B — Direct JS only:** `HORUS_DIRECT`, Prebid absent, one approved Direct\n  placement. Verify only approved provider scripts load.\n- **PILOT C — Standalone Prebid + Direct JS:** independent placements on one page.\n  Verify parallel startup and no global yield competition.\n- **PILOT D — GAM + Prebid GAM_BRIDGE:** regression profile for the established\n  GAM path. Verify GPT, targeting, GAM refresh and setup mappings.\n- **PILOT E — GAM + GAM_BRIDGE + Direct JS:** bridge placement remains GAM-owned\n  while Direct JS owns a separate non-GAM-managed placement.\n\nFor OneTag, use the provider-issued `pubId` through the normal Prebid account\nworkflow. For ExoClick, import the exact asynchronous tag and review the public\nzone/container values. For Adsterra, obtain and review the actual operator tag;\ndo not infer a script host or zone.\n\nStop immediately on secret exposure, cross-tenant access, same-container double\nrender, consent/Click Guard bypass, unexpected GPT in a GAM-less profile, or an\nuncontrolled top-window third-party script.\n''',
    'docs/GO_LIVE_CHECKLIST.md': '''\n## Task 20 GAM-less pilot gate\n\nBefore enabling a GAM-less site, require: production static config checksum;\n`HORUS_DIRECT`; at least one healthy standalone-Prebid or Direct-JS placement;\nzero renderer conflicts; privacy and Click Guard gates verified; no GPT request\nfor pure no-GAM profiles; provider account/site/placement approvals; canonical\nads.txt where required; source-aware aggregated reporting configured; rollback\nvalidated; and Operations sign-off. The production-release workflow now executes\nmigration fresh, rollback of the latest migration, and reapply before the full\nPHP suite and release archive validation.\n''',
    'docs/CONTROL_PLANE_LAUNCH_READINESS.md': '''\n## Task 20 release decision gate\n\nA GAM-less controlled pilot is blocked if standalone Prebid reaches GPT/GAM,\nDirect JS can execute arbitrary unreviewed top-window code, engine controls do\nnot isolate paths, renderer ownership can double-render, tenant/static-config\nsecrets leak, or the legacy GAM suite regresses. Production activation still\nrequires real provider approvals/IDs, infrastructure evidence, reporting\nreconciliation, and human Operations/Finance sign-off.\n''',
}

for filename, section in sections.items():
    p = Path(filename)
    if not p.exists():
        raise SystemExit(f'missing canonical doc: {filename}')
    text = p.read_text()
    marker = section.strip().splitlines()[0]
    if marker not in text:
        p.write_text(text.rstrip() + '\n' + section + '\n')
