<?php

namespace App\Services\SupplyChain;

use App\Models\DemandAdsTxtRecord;
use App\Models\SellerDeclaration;
use App\Models\Site;
use App\Services\StaticDelivery\CanonicalJson;

final class SupplyChainArtifactBuilder
{
    public function __construct(private readonly CanonicalJson $json) {}

    /** @return array<string, string> */
    public function files(): array
    {
        $files = [];
        $sites = Site::withoutGlobalScopes()->with('publisher')->orderBy('public_key')->get();
        foreach ($sites as $site) {
            $records = DemandAdsTxtRecord::withoutGlobalScopes()
                ->where(function ($query) use ($site): void {
                    $query->where('site_id', $site->id)
                        ->orWhere(function ($global) use ($site): void {
                            $global->whereNull('site_id')->whereHas('account.sites', fn ($mapping) => $mapping
                                ->where('site_id', $site->id)->where('is_enabled', true));
                        });
                })
                ->where('status', 'ACTIVE')->orderBy('domain')->orderBy('publisher_account_id')->get();
            $lines = [
                '# ads.txt 1.1 - generated by Horus Media control plane',
                'OWNERDOMAIN='.$site->primary_domain,
                'MANAGERDOMAIN='.config('supply-chain.manager_domain', 'horusmedia.net'),
            ];
            foreach ($records as $record) {
                $line = implode(', ', array_filter([
                    $record->domain, $record->publisher_account_id, strtoupper($record->relationship), $record->certification_authority_id,
                ], fn ($value) => filled($value)));
                if ($line !== '') $lines[] = $line;
            }
            $contents = implode("\n", array_values(array_unique($lines)))."\n";
            $files['supply/sites/'.$site->public_key.'/ads.txt'] = $contents;
            $files['supply/domains/'.$this->safeDomain($site->primary_domain).'/ads.txt'] = $contents;
        }

        $sellers = SellerDeclaration::withoutGlobalScopes()->where('status', 'ACTIVE')->orderBy('seller_id')->get()->map(
            fn ($seller) => array_filter([
                'seller_id' => $seller->seller_id,
                'seller_type' => strtoupper($seller->seller_type),
                'name' => $seller->is_confidential ? null : $seller->name,
                'domain' => $seller->is_confidential ? null : $seller->domain,
                'is_confidential' => $seller->is_confidential ? 1 : 0,
            ], fn ($value) => $value !== null),
        )->values()->all();
        $sellerPayload = [
            'contact_email' => config('supply-chain.contact_email'),
            'contact_address' => config('supply-chain.contact_address'),
            'version' => '1.0',
            'sellers' => $sellers,
        ];
        if (filled(config('supply-chain.tag_id'))) {
            $sellerPayload['identifiers'] = [['name' => 'TAG-ID', 'value' => config('supply-chain.tag_id')]];
        }
        $files['supply/sellers.json'] = $this->json->encode($sellerPayload);

        return $files;
    }

    private function safeDomain(string $domain): string
    {
        return preg_replace('/[^a-z0-9.-]/', '', strtolower($domain)) ?: 'invalid';
    }
}
