<?php

namespace App\Services\SupplyChain;

use App\Models\Site;
use App\Services\StaticDelivery\CanonicalJson;

final class SupplyChainArtifactBuilder
{
    public function __construct(
        private readonly CanonicalJson $json,
        private readonly SupplyChainStandardsContract $contract,
        private readonly SellersJsonValidator $sellersValidator,
    ) {}

    /** @return array<string, string> */
    public function files(): array
    {
        $files = [];
        $sites = Site::withoutGlobalScope('organization')->with('publisher')->orderBy('public_key')->get();
        foreach ($sites as $site) {
            $contents = $this->adsTxtForSite($site);
            $files['supply/sites/'.$site->public_key.'/ads.txt'] = $contents;
            $files['supply/domains/'.$this->safeDomain($site->primary_domain).'/ads.txt'] = $contents;
        }
        $sellersJson = $this->sellersJson();
        $files['sellers.json'] = $sellersJson;
        $files['supply/sellers.json'] = $sellersJson;
        return $files;
    }

    /** @return array<string, mixed> */
    public function sellersJsonPayload(): array
    {
        $payload = [
            'version' => '1.0',
            'sellers' => collect($this->contract->sellers()['sellers'])->map(
                fn (array $seller): array => array_filter($seller['payload'], fn ($value) => $value !== null),
            )->values()->all(),
        ];
        $email = trim((string) config('supply-chain.contact_email'));
        $address = trim((string) config('supply-chain.contact_address'));
        $tagId = trim((string) config('supply-chain.tag_id'));
        if ($email !== '') { $payload['contact_email'] = $email; }
        if ($address !== '') { $payload['contact_address'] = $address; }
        if ($tagId !== '') { $payload['identifiers'] = [['name' => 'TAG-ID', 'value' => $tagId]]; }
        $this->sellersValidator->assertValid($payload);
        return $payload;
    }

    public function sellersJson(): string
    {
        return $this->json->encode($this->sellersJsonPayload());
    }

    /** @param array{records: array, entries?: array, lines: array, findings: array}|null $adsTxt */
    public function adsTxtForSite(Site $site, ?array $adsTxt = null): string
    {
        $adsTxt ??= $this->contract->adsTxtForSite($site);
        $records = $adsTxt['lines'] === []
            ? ['placeholder.example.com, placeholder, DIRECT, placeholder']
            : $adsTxt['lines'];
        $directives = ['# ads.txt 1.1 - generated by Horus Media control plane'];
        $ownerDomain = $this->contract->ownerDomainForSite($site);
        if ($ownerDomain !== null) { $directives[] = 'OWNERDOMAIN='.$ownerDomain; }
        $manager = $this->contract->managerDirectiveForSite($site);
        if ($manager !== null) { $directives[] = $manager['line']; }
        $directives = array_merge($directives, $this->contract->optionalDirectivesForSite($site));
        return implode("\n", array_merge(array_values(array_unique($directives)), $records))."\n";
    }

    private function safeDomain(string $domain): string
    {
        return preg_replace('/[^a-z0-9.-]/', '', strtolower($domain)) ?: 'invalid';
    }
}
