<?php

namespace App\Services\SupplyChain;

use App\Models\Site;
use App\Services\StaticDelivery\CanonicalJson;

final class SupplyChainArtifactBuilder
{
    public function __construct(
        private readonly CanonicalJson $json,
        private readonly SupplyChainInvariantService $invariants,
    ) {}

    /** @return array<string, string> */
    public function files(): array
    {
        $files = [];
        $sites = Site::withoutGlobalScope('organization')->with('publisher')->orderBy('public_key')->get();
        foreach ($sites as $site) {
            $owner = $this->invariants->ownerIdentity($site);
            $adsTxt = $this->invariants->adsTxtForSite($site);
            $lines = [
                '# ads.txt 1.1 - generated by Horus Media control plane',
                'OWNERDOMAIN='.$owner['domain'],
                'MANAGERDOMAIN='.$this->invariants->managerDomain(),
            ];
            $contents = implode("\n", array_merge($lines, $adsTxt['lines']))."\n";
            $files['supply/sites/'.$site->public_key.'/ads.txt'] = $contents;
            $files['supply/domains/'.$this->safeDomain($site->primary_domain).'/ads.txt'] = $contents;
        }

        $sellers = collect($this->invariants->sellers()['sellers'])->map(
            fn (array $seller): array => array_filter($seller['payload'], fn ($value) => $value !== null),
        )->values()->all();
        $sellerPayload = [
            'contact_email' => config('supply-chain.contact_email'),
            'contact_address' => config('supply-chain.contact_address'),
            'version' => '1.0',
            'sellers' => $sellers,
        ];
        if (filled(config('supply-chain.tag_id'))) {
            $sellerPayload['identifiers'] = [['name' => 'TAG-ID', 'value' => config('supply-chain.tag_id')]];
        }
        $files['supply/sellers.json'] = $this->json->encode($sellerPayload);

        return $files;
    }

    private function safeDomain(string $domain): string
    {
        return preg_replace('/[^a-z0-9.-]/', '', strtolower($domain)) ?: 'invalid';
    }
}
