@extends('layouts.admin')
@section('title', $account->exists ? 'Edit '.ucfirst($kind) : 'New '.ucfirst($kind))
@section('heading', $account->exists ? 'Edit '.ucfirst($kind) : 'New '.ucfirst($kind))
@section('navigation')<a href="{{ route('admin.'.$kind.'s.index') }}">{{ ucfirst($kind) }}s</a><span class="active">Details</span>@endsection
@section('content')
<article><form method="POST" action="{{ $account->exists ? route('admin.'.$kind.'s.update', $account) : route('admin.'.$kind.'s.store') }}" class="form-grid">@csrf @if($account->exists)@method('PUT')@endif
<label>Legal name<input class="hm-input" name="legal_name" value="{{ old('legal_name', $account->legal_name) }}" required></label><label>Display name<input class="hm-input" name="display_name" value="{{ old('display_name', $account->display_name) }}" required></label>
<label>Organization slug<input class="hm-input" name="organization_slug" value="{{ old('organization_slug', $account->organization?->slug) }}" required></label><label>Billing email<input class="hm-input" type="email" name="billing_email" value="{{ old('billing_email', $account->billing_email) }}"></label>
<label>Status<select class="hm-input" name="status">@foreach(\App\Enums\AccountStatus::cases() as $status)<option @selected(old('status', $account->status?->value)===$status->value)>{{ $status->value }}</option>@endforeach</select></label><label>Dashboard title<input class="hm-input" name="dashboard_title" value="{{ old('dashboard_title', $account->dashboard_title) }}"></label>
<label>Primary color<input class="hm-input" name="primary_color" value="{{ old('primary_color', $account->primary_color) }}" placeholder="#12499d"></label><label class="full">Internal notes<textarea class="hm-input" name="internal_notes" rows="5">{{ old('internal_notes', $account->internal_notes) }}</textarea></label>
@foreach($errors->all() as $error)<p class="error full">{{ $error }}</p>@endforeach<button class="hm-button-primary">Save {{ $kind }}</button></form></article>
@if($account->exists)<article><h2>Contacts</h2>
@foreach($account->contacts as $contact)<form method="POST" action="{{ route('admin.'.$kind.'s.contacts.update', [$account, $contact]) }}" class="contact-row">@csrf @method('PUT')<input class="hm-input" name="name" value="{{ $contact->name }}" required><input class="hm-input" type="email" name="email" value="{{ $contact->email }}" required><input class="hm-input" name="phone" value="{{ $contact->phone }}" placeholder="Phone"><input class="hm-input" name="title" value="{{ $contact->title }}" placeholder="Title"><label><input type="checkbox" name="is_primary" value="1" @checked($contact->is_primary)> Primary</label><button class="hm-button-secondary">Update</button></form><form method="POST" action="{{ route('admin.'.$kind.'s.contacts.destroy', [$account, $contact]) }}">@csrf @method('DELETE')<button class="text-button error">Delete {{ $contact->name }}</button></form>@endforeach
<h3>Add contact</h3><form method="POST" action="{{ route('admin.'.$kind.'s.contacts.store', $account) }}" class="form-grid">@csrf<label>Name<input class="hm-input" name="name" required></label><label>Email<input class="hm-input" type="email" name="email" required></label><label>Phone<input class="hm-input" name="phone"></label><label>Title<input class="hm-input" name="title"></label><label><input type="checkbox" name="is_primary" value="1"> Primary</label><button class="hm-button-primary">Add contact</button></form></article>@endif
@if($account->exists && $kind === 'publisher')<section class="detail-grid"><article><h2>Onboarding review</h2><p>Submitted: {{ $account->onboarding_submitted_at ?: 'Not submitted' }}</p><form method="POST" action="{{ route('admin.publishers.review', $account) }}" class="form-stack">@csrf<select class="hm-input" name="decision"><option>APPROVE</option><option>REJECT</option></select><textarea class="hm-input" name="reason" placeholder="Required review reason" required></textarea><button class="hm-button-secondary">Record publisher review</button></form></article><article><h2>Commercial records</h2><a class="hm-button-primary button-link" href="{{ route('admin.publishers.contracts.index', $account) }}">Manage contracts</a>@if(auth()->user()->hasPermission('publisher_payments.manage'))<a class="hm-button-secondary button-link" href="{{ route('admin.publishers.payment-profile.edit', $account) }}">Payment profile</a>@endif</article></section>@endif
@if($account->exists)<form method="POST" action="{{ route('admin.'.$kind.'s.destroy', $account) }}">@csrf @method('DELETE')<button class="text-button error">Delete {{ $kind }}</button></form>@endif
@endsection
